-- EXC 1

SELECT EMP_NO, COGNOM, SALARI*14 AS "Sou_Anual"
FROM EMP ;

-- EXC 2

SELECT EMP_NO, COGNOM, SALARI*14/166.386 AS "Sou_Anual"
FROM EMP ;

-- EXC 3

SELECT EMP_NO, DATA_ALTA
FROM EMP 
WHERE DATA_ALTA > '01/06/81' ;

-- EXC 4

SELECT EMP_NO, DATA_ALTA, SALARI
FROM EMP 
WHERE DATA_ALTA > '01/06/81' and SALARI > '200000' ;

-- EXC 5

SELECT EMP_NO, COGNOM
FROM EMP
WHERE UPPER(COGNOM) LIKE 'S%' ;

-- EXC 6

SELECT EMP_NO, COGNOM
FROM EMP
WHERE UPPER(COGNOM) LIKE 'S%' and LOWER(COGNOM) LIKE 's%' ;

-- EXC 7

SELECT EMP_NO, COGNOM
FROM EMP
WHERE SUBSTR(COGNOM, 3) LIKE 'm%' ;

-- EXC 8

SELECT EMP_NO, DATA_ALTA
FROM EMP
ORDER BY DATA_ALTA ASC ;

-- EXC 9

SELECT COM_NUM, DETALL_NUM, PREU_VENDA*QUANTITAT AS "IMPORT"
FROM DETALL ;

-- EXC 10

SELECT EMP_NO, COGNOM, DATA_ALTA
FROM EMP
WHERE LOWER(COGNOM) NOT LIKE '%ez' AND DATA_ALTA > '01/01/81' AND DATA_ALTA < '31/12/81' ;

-- EXC 11

SELECT EMP_NO, COGNOM, DEPT_NO
FROM EMP
WHERE DEPT_NO IN (10,30) ;

-- EXC 12

SELECT COGNOM, OFICI, COMISSIO
FROM EMP
WHERE COMISSIO IN (NULL, 0) ;

-- EXC 13

SELECT EMP_NO, COGNOM, DEPT_NO
FROM EMP
WHERE DEPT_NO NOT IN (10,30) ;

