-- EXC 1

SELECT EMP_NO, COGNOM, DATA_ALTA, SALARI, SALARI+COMISSIO AS "SALARI_TOTAL" -- Ho he fet així per que si no, qui no cobra comissions surt en valor NULL.
FROM EMP ;

-- EXC 2

SELECT COGNOM, OFICI, DEPT_NO
FROM EMP
WHERE DEPT_NO IN (30, 40) ;

-- EXC 3

SELECT *
FROM CLIENT 
WHERE UPPER(NOM) LIKE '%SPORT%' ;

-- EXC 4

SELECT 'A l’atenció de ' || NOM || 'li enviarem la comanda a l’adreça ' || DOMICILI || 'de ' || CIUTAT AS ANUNCI
FROM CLIENT ;

-- EXC 5

SELECT INSCRIPCIO, COGNOM, DATA_NAIX
FROM MALALT
WHERE UPPER(COGNOM) LIKE 'F%' ;

-- EXC 6

SELECT EMP_NO, COGNOM, SALARI/166.386 AS "SALARI" 
FROM EMP
WHERE SALARI BETWEEN 150000 AND 200000 ;

-- EXC 7

SELECT EMP_NO, COGNOM, SALARI/166.386 AS "SALARI" , DATA_ALTA
FROM EMP
WHERE SALARI BETWEEN 150000 AND 200000 ;

-- EXC 8

SELECT EMPLEAT_NO, FUNCIO, TORN
FROM PLANTILLA
WHERE FUNCIO NOT LIKE 'Infermer' AND TORN LIKE 'N';

-- EXC 9

SELECT HOSPITAL_COD, DOCTOR_NO, ESPECIALITAT
FROM DOCTOR
WHERE HOSPITAL_COD = 22 AND ESPECIALITAT IN ('Cardiologia', 'Ginecologia', 'Pediatria', 'Neurologia');

-- EXC 10

SELECT INSCRIPCIO, COGNOM, SEXE
FROM MALALT
WHERE COGNOM NOT LIKE '%M.' AND SEXE NOT LIKE 'H';

-- EXC 11

SELECT CLIENT_COD, CIUTAT, LIMIT_CREDIT
FROM CLIENT
WHERE CIUTAT IN ('PALO ALTO', 'BURLINGAME') AND LIMIT_CREDIT > 5000;

-- EXC 12

SELECT EMP_NO, DATA_ALTA
FROM EMP
WHERE DATA_ALTA BETWEEN '01/01/82' AND '31/12/82';

-- EXC 13

SELECT INSCRIPCIO, COGNOM, DATA_NAIX
FROM MALALT
WHERE COGNOM BETWEEN 'A' AND 'F'
AND DATA_NAIX BETWEEN '01/01/35' AND '01/01/45';

-- EXC 14

SELECT CLIENT_COD, NOM, LIMIT_CREDIT, CIUTAT, ESTAT, AREA
FROM CLIENT
WHERE ESTAT IN ('CA', 'MN') AND AREA != '408' AND CIUTAT NOT LIKE 'BELMONT';

-- EXC 15

SELECT COGNOM, OFICI, DEPT_NO
FROM EMP
WHERE DEPT_NO NOT IN ('10', '20', '80');

-- EXC 16

SELECT COGNOM, OFICI, COMISSIO, DEPT_NO
FROM EMP
WHERE DEPT_NO IN ('10', '20', '80') AND COMISSIO = '0';

-- EXC 17

SELECT COGNOM, OFICI, COMISSIO, DEPT_NO
FROM EMP
WHERE DEPT_NO IN ('10', '20', '80') AND COMISSIO <= '1';

-- EXC 18